name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
          node -v
          npm i

    - name: Deploy
      run: npm run deploy
